apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kiosk-gui
  namespace: kiosk
  labels:
    app.kubernetes.io/name: kiosk-gui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kiosk-gui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kiosk-gui
    spec:
      nodeSelector:
        kubernetes.io/hostname: debian-kde
      containers:
        - name: kiosk-gui
          # Image need to be imported on node, see Makefile.
          image: lab-firefox
          imagePullPolicy: Never
          volumeMounts:
            - name: x11
              mountPath: /tmp/.X11-unix
          env:
            - name: DISPLAY
              value: :0
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 65534
      volumes:
        - name: x11
          hostPath:
            path: /tmp/.X11-unix
