apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoin-core-34293327
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hc-volume
  capacity:
    storage: 465Gi # 500GB
  local:
    path: /mnt/HC_Volume_34293327
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-worker-1
