apiVersion: v1
kind: Service
metadata:
  name: bitcoin-core
  labels:
    app.kubernetes.io/name: bitcoin-core
spec:
  selector:
    app.kubernetes.io/name: bitcoin-core
  ports:
    - name: rpc
      port: 8332
      protocol: TCP
    - name: p2p
      port: 8333
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-core
  labels:
    app.kubernetes.io/name: bitcoin-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitcoin-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitcoin-core
    spec:
      containers:
        - name: bitcoin-core
          image: ruimarinho/bitcoin-core:23.0
          command:
            - bitcoind
            - -printtoconsole
            - -rpcbind=0.0.0.0
            - -rpcallowip=0.0.0.0/0
            - -rpcauth='$(BITCOIN_RPC_AUTH)'
          envFrom:
            - secretRef:
                name: bitcoin-core
          volumeMounts:
            - name: bitcoin-core
              mountPath: /root/.bitcoin
  volumeClaimTemplates:
    - metadata:
        name: bitcoin-core
        labels:
          app.kubernetes.io/name: bitcoin-core
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: hc-volume
        resources:
          requests:
            storage: 465Gi
