apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      access:
        enabled: true

    deployment:
      kind: DaemonSet

    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0

    service:
      enabled: false

    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443
        tls:
          enable: true
          certResolver: letsencrypt

    providers:
      kubernetesCRD:
        allowCrossNamespace: true

    ingressRoute:
      dashboard:
        entryPoints:
          - websecure
        matchRule: Host(`traefik.ulexxander.work`)
        middlewares:
          - name: basic-auth

    certResolvers:
      letsencrypt:
        email: ulexxander@gmail.com
        storage: /data/acme.json
        httpChallenge:
          entryPoint: web

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 128Mi
      storageClass: local-path
