# TODO: prom metrics.

# https://artifacthub.io/packages/helm/grafana/grafana/6.58.7
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: monitoring
spec:
  repo: https://grafana.github.io/helm-charts
  chart: grafana
  version: 6.58.7
  valuesContent: |-
    ingress:
      enabled: true
      ingressClassName: traefik
      pathType: ImplementationSpecific
      path: ""
      hosts:
        - grafana.ulexxander.work
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure

    persistence:
      type: pvc
      enabled: true
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      size: 10Gi
