# https://artifacthub.io/packages/helm/prometheus-community/prometheus/23.2.0
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: monitoring
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus
  version: 23.2.0
  valuesContent: |-
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        pathType: ImplementationSpecific
        path: ""
        hosts:
          - prometheus.ulexxander.work
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: kube-system-basic-auth@kubernetescrd
      
      persistentVolume:
        enabled: true
        storageClass: local-path
        accessModes:
          - ReadWriteOnce
        size: 8Gi

    alertmanager:
      enabled: false

    kube-state-metrics:
      enabled: true
      # In case you get IP that is banned by registry.k8s.io
      # happened to me once on Hetzner:
      # image:
      #   registry: docker.io
      #   repository: bitnami/kube-state-metrics
      #   tag: 2.9.2

    prometheus-node-exporter:
      enabled: true
      fullnameOverride: prometheus-node-exporter

    prometheus-pushgateway:
      enabled: true
      fullnameOverride: prometheus-pushgateway
