# TODO: prom metrics.

# https://artifacthub.io/packages/helm/grafana/promtail/6.14.1
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: promtail
  namespace: monitoring
spec:
  repo: https://grafana.github.io/helm-charts
  chart: promtail
  version: 6.14.1
  valuesContent: |-
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
