global:
  scrape_interval: 10s

scrape_configs:
  - job_name: docker_sd

    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - action: keep
        source_labels:
          - __meta_docker_container_label_prometheus_io_scrape
        regex: true

      - source_labels:
          - __meta_docker_container_label_prometheus_io_path
        regex: (.+)
        target_label: __metrics_path__

      - source_labels:
          - __address__
          - __meta_docker_container_label_prometheus_io_port
        regex: (.*):(\d+);(\d+)
        replacement: ${1}:${3}
        target_label: __address__

      - source_labels:
          - __meta_docker_container_id
        target_label: container_id

      - source_labels:
          - __meta_docker_container_name
        target_label: container_name
