version: "3.8"

services:
  # docker compose run --rm debug
  debug:
    image: alpine:3.18.4
    profiles:
      - debug

  whoami-external:
    image: traefik/whoami:v1.10.1
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami-external.entrypoints=ext-https
      - traefik.http.routers.whoami-external.rule=Host(`whoami.ulexxander.work`)

  whoami-internal:
    image: traefik/whoami:v1.10.1
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami-internal.entrypoints=int-http
      - traefik.http.routers.whoami-internal.rule=Host(`whoami.internal.ulexxander.work`)

  traefik:
    image: traefik:2.10.4
    ports:
      # Extenral entrypoints.
      - 188.34.198.254:80:80
      - 188.34.198.254:443:443
      # Internal entrypoints.
      - 127.0.0.1:80:1080
      - 127.0.0.1:443:1443
    volumes:
      - traefik-acme-data:/acme
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.entrypoints=int-http
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.internal.ulexxander.work`)
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.middlewares=auth-errors,auth-proxy

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.0
    command:
      - --http-address=:4180
      - --email-domain=*
      - --provider=oidc
      - --oidc-issuer-url=https://keycloak.ulexxander.work/realms/master
      - --code-challenge-method=S256
      - --reverse-proxy
      - --cookie-secure=false
    # Must contain:
    # OAUTH2_PROXY_CLIENT_ID
    # OAUTH2_PROXY_CLIENT_SECRET
    # OAUTH2_PROXY_COOKIE_SECRET
    env_file: oauth2-proxy.env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.oauth2-proxy.entrypoints=int-http
      - traefik.http.routers.oauth2-proxy.rule=HostRegexp(`{wildcard:[a-z]+}.internal.ulexxander.work`) && PathPrefix(`/oauth2`)
      - traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180
      - traefik.http.middlewares.auth-proxy.forwardauth.address=http://oauth2-proxy:4180/oauth2/auth
      - traefik.http.middlewares.auth-proxy.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.auth-errors.errors.service=oauth2-proxy@docker
      - traefik.http.middlewares.auth-errors.errors.status=401-403
      - traefik.http.middlewares.auth-errors.errors.query=/oauth2/sign_in

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command:
      - start
      # Currently does not work with this option.
      # - --optimized
    env_file: keycloak.env
    environment:
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME_URL=https://keycloak.ulexxander.work
    restart: always
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.entrypoints=ext-https
      - traefik.http.routers.keycloak.rule=Host(`keycloak.ulexxander.work`)
      - prometheus.io/scrape=true
      - prometheus.io/port=8787

  keycloak-postgres:
    image: postgres:15.4
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    env_file: keycloak-postgres.env
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 3

  headscale:
    image: headscale/headscale:0.22
    command:
      - headscale
      - serve
    volumes:
      - headscale-data:/var/lib/headscale
      - ./headscale.yaml:/etc/headscale/config.yaml
      - ./headscale-client-secret.txt:/etc/headscale/client-secret.txt
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.headscale.entrypoints=ext-https
      - traefik.http.routers.headscale.rule=Host(`headscale.ulexxander.work`)
      - traefik.http.services.headscale.loadbalancer.server.port=8080
      - prometheus.io/scrape=true
      - prometheus.io/port=9090

  # NOTE: outgoing connections to other peers isn't working because of userspace mode.
  tailscale:
    image: tailscale/tailscale:v1.50.1
    network_mode: host
    # cap_add: # For non-userspace mode.
    #   - NET_ADMIN
    #   - NET_RAW
    volumes:
      - tailscale-data:/var/lib/tailscale
      # - /dev/net/tun:/dev/net/tun # For non-userspace mode.
    env_file: tailscale.env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      - TS_EXTRA_ARGS=--login-server=https://headscale.ulexxander.work
      # - TS_ACCEPT_DNS=true # Probably also requires to run in non-userspace mode.
    restart: always

  grafana:
    image: grafana/grafana:10.1.2
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasources:/etc/grafana/provisioning/datasources
    user: root
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=int-http
      - traefik.http.routers.grafana.rule=Host(`grafana.internal.ulexxander.work`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - prometheus.io/scrape=true
    env_file: grafana.env
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.internal.ulexxander.work
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid email profile
      - GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH=email
      - GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH=preferred_username
      - GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH=name
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://keycloak.ulexxander.work/realms/master/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://keycloak.ulexxander.work/realms/master/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://keycloak.ulexxander.work/realms/master/protocol/openid-connect/userinfo
      - GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN=true
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=email == 'ulexxander@gmail.com' && 'GrafanaAdmin'
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT=true

  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.entrypoints=int-http
      - traefik.http.routers.prometheus.rule=Host(`prometheus.internal.ulexxander.work`)
      - traefik.http.routers.prometheus.middlewares=auth-errors,auth-proxy
      - prometheus.io/scrape=true

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    privileged: true
    command:
      - -store_container_labels=false
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.cadvisor.entrypoints=int-http
      - traefik.http.routers.cadvisor.rule=Host(`cadvisor.internal.ulexxander.work`)
      - traefik.http.routers.cadvisor.middlewares=auth-errors,auth-proxy
      - prometheus.io/scrape=true

  node-exporter:
    image: prom/node-exporter:v1.6.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    restart: always
    labels:
      - prometheus.io/scrape=true

volumes:
  traefik-acme-data:
  keycloak-postgres-data:
  headscale-data:
  tailscale-data:
  grafana-data:
  prometheus-data:
