accessLog: {}

api: {}

metrics:
  prometheus: {}

entryPoints:
  ext-http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: ext-https
          scheme: https
  ext-https:
    address: :443
    http:
      tls:
        certResolver: main

  int-http:
    address: :1080
    # http:
    #   redirections:
    #     entryPoint:
    #       to: int-https
    #       scheme: https
  int-https:
    address: :1443
    # DNS challenge needed in order for it to work.

certificatesResolvers:
  main:
    acme:
      email: ulexxander@gmail.com
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: ext-http

providers:
  docker:
    exposedByDefault: false
